/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doublepmcl.nn.neuralnetworknetbeansjava;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.nio.file.Paths;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author haris
 */
public class LearnDigitRecognizer extends javax.swing.JFrame
{
    private final JFileChooser fileChooser = new JFileChooser(Paths.get("").toAbsolutePath().toString());
    /**
     * Creates new form ShowNumbersGUI
     */
    public LearnDigitRecognizer()
    {
        fileChooser.setPreferredSize(new Dimension(fileChooser.getPreferredSize().width + 100, fileChooser.getPreferredSize().height + 100));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoadImage = new javax.swing.JButton();
        labelPicture = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuitemFile = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();
        menuitemAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn Neural-Network for digit recognition");
        setMinimumSize(new java.awt.Dimension(530, 350));
        setPreferredSize(new java.awt.Dimension(530, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoadImage.setText("Load Image");
        btnLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 220, -1));

        labelPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 280));

        menuFile.setText("File");

        menuitemFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuitemFile.setText("File");
        menuFile.add(menuitemFile);

        menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuitemExit.setText("Exit");
        menuFile.add(menuitemExit);

        jMenuBar1.add(menuFile);

        menuitemAbout.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuitemAbout.add(jMenuItem1);

        jMenuBar1.add(menuitemAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImageActionPerformed
        // TODO add your handling code here:
//        Path currentRelativePath = Paths.get("");
//        String s = currentRelativePath.toAbsolutePath().toString();
//        System.out.println("Current relative path is: " + s);
//        JOptionPane.showMessageDialog(this, "Eggs are not supposed to be green.\n Working dir is: "+s);
//        fileChooser.
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            try {
//                ImageIcon icon = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
//                BufferedImage buffImg = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
//                Graphics g = buffImg.getGraphics();
////                Graphics g = buffImg.createGraphics();
//                icon.paintIcon(this, g, 0, 0);
//                buffImg.setRGB(50, 100, new Color(20, 40, 50).getRGB());
                BufferedImage buffImg = ImageIO.read(new File(fileChooser.getSelectedFile().getAbsolutePath()));
                int width = buffImg.getWidth();
                int height = buffImg.getHeight();
                int scale = 10;
                BufferedImage imgBigger = new BufferedImage(buffImg.getWidth()*scale, buffImg.getHeight()*scale, BufferedImage.TYPE_INT_RGB);
                for (int j =0; j < height; j++) {
                    for (int i = 0; i < width; i++) {
                        for (int jk = 0; jk < scale; jk++) {
                            for (int ji = 0; ji < scale; ji++) {
                                imgBigger.setRGB(i*scale+ji, j*scale+jk, buffImg.getRGB(i, j));
                            }
                        }
                    }
                }
                labelPicture.setIcon(new ImageIcon(imgBigger));//buffImg));
            } catch (Exception e) {

            }   
        }
    }//GEN-LAST:event_btnLoadImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LearnDigitRecognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LearnDigitRecognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LearnDigitRecognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LearnDigitRecognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LearnDigitRecognizer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoadImage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuitemAbout;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemFile;
    // End of variables declaration//GEN-END:variables
}
