/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doublepmcl.nn.neuralnetworknetbeansjava;

import java.awt.Color;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author haris
 */
public class ShowNumbersGUI extends javax.swing.JFrame
{

    /**
     * Creates new form ShowNumbersGUI
     */
    public ShowNumbersGUI()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new java.awt.Panel();
        btnChangeWindowSize = new java.awt.Button();
        btnLoadImage = new javax.swing.JButton();
        labelPicture = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuitemFile = new javax.swing.JMenuItem();
        menuitemExit = new javax.swing.JMenuItem();
        menuitemAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 230));

        btnChangeWindowSize.setLabel("Change window size");
        btnChangeWindowSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeWindowSizeActionPerformed(evt);
            }
        });
        getContentPane().add(btnChangeWindowSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, -1));

        btnLoadImage.setText("Load Image");
        btnLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        labelPicture.setBackground(new java.awt.Color(153, 0, 153));
        labelPicture.setForeground(new java.awt.Color(0, 153, 102));
        getContentPane().add(labelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 210, 230));

        menuFile.setText("File");

        menuitemFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuitemFile.setText("File");
        menuFile.add(menuitemFile);

        menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuitemExit.setText("Exit");
        menuFile.add(menuitemExit);

        jMenuBar1.add(menuFile);

        menuitemAbout.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuitemAbout.add(jMenuItem1);

        jMenuBar1.add(menuitemAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnChangeWindowSizeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChangeWindowSizeActionPerformed
    {//GEN-HEADEREND:event_btnChangeWindowSizeActionPerformed
        // TODO add your handling code here:
        Color c = panelMain.getBackground();
        panelMain.setBackground(new Color((c.getRed()+1)%256, (c.getGreen()+Math.abs((new Random()).nextInt()))%256, (c.getBlue() + 2)%256));
    }//GEN-LAST:event_btnChangeWindowSizeActionPerformed

    private void btnLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImageActionPerformed
        // TODO add your handling code here:
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
//        System.out.println("Current relative path is: " + s);
        JOptionPane.showMessageDialog(this, "Eggs are not supposed to be green.\n Working dir is: "+s);
        try {
            String path = "images/test.png";
            ImageIcon icon = new ImageIcon(path);
            labelPicture.setIcon(icon);
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnLoadImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ShowNumbersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ShowNumbersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ShowNumbersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ShowNumbersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ShowNumbersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnChangeWindowSize;
    private javax.swing.JButton btnLoadImage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelPicture;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuitemAbout;
    private javax.swing.JMenuItem menuitemExit;
    private javax.swing.JMenuItem menuitemFile;
    private java.awt.Panel panelMain;
    // End of variables declaration//GEN-END:variables
}
